spring:
  application:
    name: customer
  profiles:
    active: production
  datasource:
    url: ${customer.datasource.url}
    username: ${customer.datasource.username}
    password: ${customer.datasource.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${customer.datasource.ddl-mode}

# ACTUATOR INFO
info:
  app:
    name: "customer"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}


management:
  endpoints:
    web:
      cors:
        allowed-origins: '*'
      exposure:
        include: '*'
#eureka:
#  client: ${eureka-client}

feign:
  hystrix:
    enabled: true

accounts:
  ribbon:
    eureka:
      enabled: false

    listOfServers: localhost:9999,localhost:9998